#!/bin/bash
#
# MindGate MVP1 Installer
#
# Steps:
#   1. Builds release binaries (`mindgated` daemon & `mindgate` CLI).
#   2. Installs binaries to /usr/local/bin (root-owned).
#   3. Creates /etc/mindgate and owner.env for non-root IPC authorization.
#   4. Installs Native Messaging Hosts globally across all Chromium browsers.
#   5. Configures systemd services for both Daemon and Watchdog.

set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
  echo "Error: Must be run with sudo: sudo ./install.sh" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_BIN_DIR="/usr/local/bin"
CONFIG_DIR="/etc/mindgate"

REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo root)}"
REAL_HOME="$(getent passwd "${REAL_USER}" | cut -d: -f6)"

# PERMANENT Extension ID (locked via manifest.json "key")
EXTENSION_ID="gpdnmbmmmlgopipgnddldnihapebjkfn"

echo "[1/5] Building release binaries..."
cd "${REPO_ROOT}"
# cargo build --release

echo "[2/5] Installing binaries to ${INSTALL_BIN_DIR}..."
install -o root -g root -m 755 target/release/mindgated "${INSTALL_BIN_DIR}/mindgated"
install -o root -g root -m 755 target/release/mindgate  "${INSTALL_BIN_DIR}/mindgate"
echo "  ✓ Binaries installed."

echo "[3/5] Setting up configuration directory (${CONFIG_DIR})..."
mkdir -p "${CONFIG_DIR}"
chown root:root "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

REAL_UID="$(id -u "${REAL_USER}")"
echo "MINDGATE_OWNER_UID=${REAL_UID}" > "${CONFIG_DIR}/owner.env"
chmod 644 "${CONFIG_DIR}/owner.env"
echo "  ✓ Configuration directory ready."

echo "[4/5] Generating Native Messaging Bridge & Manifests..."
BRIDGE_SCRIPT="${INSTALL_BIN_DIR}/mindgate-bridge.sh"
cat > "${BRIDGE_SCRIPT}" <<BRIDGE_EOF
#!/bin/bash
# Generated by MindGate install.sh — do not hand-edit.
exec 2>>/var/log/mindgate-bridge-error.log
exec "${INSTALL_BIN_DIR}/mindgate" nativebridge
BRIDGE_EOF
chmod 755 "${BRIDGE_SCRIPT}"
chown root:root "${BRIDGE_SCRIPT}"

NMH_MANIFEST_NAME="com.mindgate.protector.json"

# GLOBAL directories (Most reliable, applies to all users/profiles of the browser)
declare -a GLOBAL_NMH_DIRS=(
  "/etc/opt/chrome/native-messaging-hosts"
  "/etc/chromium/native-messaging-hosts"
  "/etc/opt/brave/native-messaging-hosts"
  "/etc/vivaldi/native-messaging-hosts"
  "/etc/opt/microsoft-edge/native-messaging-hosts"
)

for dir in "${GLOBAL_NMH_DIRS[@]}"; do
  parent="$(dirname "${dir}")"
  # Create directory if parent exists (e.g., /etc/opt or /etc)
  if [[ -d "${parent}" ]] || [[ "${parent}" == "/etc/opt" ]] || [[ "${parent}" == "/etc" ]]; then
    mkdir -p "${dir}"
    cat > "${dir}/${NMH_MANIFEST_NAME}" <<MANIFEST_EOF
{
  "name": "com.mindgate.protector",
  "description": "MindGate Native Messaging Bridge",
  "path": "${BRIDGE_SCRIPT}",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://${EXTENSION_ID}/"
  ]
}
MANIFEST_EOF
    chmod 644 "${dir}/${NMH_MANIFEST_NAME}"
    echo "  -> Installed global manifest in ${dir}"
  fi
done

echo "[5/5] Registering and starting systemd services..."
install -m 644 "${REPO_ROOT}/installer/systemd/mindgated.service" \
  /etc/systemd/system/mindgated.service
install -m 644 "${REPO_ROOT}/installer/systemd/mindgate-watchdog.service" \
  /etc/systemd/system/mindgate-watchdog.service
install -m 755 "${REPO_ROOT}/installer/mindgate-watchdog.sh" \
  "${INSTALL_BIN_DIR}/mindgate-watchdog.sh"
install -m 755 "${REPO_ROOT}/installer/uninstall.sh" \
  "${INSTALL_BIN_DIR}/mindgate-uninstall.sh"

systemctl daemon-reload
systemctl enable mindgated.service mindgate-watchdog.service
systemctl restart mindgated.service
systemctl restart mindgate-watchdog.service

echo
echo "=========================================================="
echo " MindGate installation complete!"
echo " Daemon & Watchdog services are live and enabled on boot."
echo "=========================================================="
echo
echo "To finish setup:"
echo " 1. Completely close all Chrome/Chromium windows."
echo " 2. Open Chrome and go to chrome://extensions."
echo " 3. Remove the old MindGate extension if it exists."
echo " 4. Enable 'Developer mode' and click 'Load unpacked'."
echo " 5. Select the 'extension/' directory in this repository."
echo " 6. Enable 'Allow in Incognito' for full protection."
echo
echo "Run 'mindgate doctor' to check connection status."