#!/bin/bash
#
# MindGate installer — production hardening pass.
#
# What this does, in order:
#   1. Builds the daemon + CLI in release mode.
#   2. Installs both binaries to /usr/local/bin, root-owned.
#   3. Creates /etc/mindgate (root-owned, 700) for rules.toml/lock.toml.
#   4. Generates a PRODUCTION native-messaging bridge script and
#      manifest — mindgate.sh / com.mindgate.protector.json as
#      checked into the repo hardcode dev paths (/tmp/mindgate-dev,
#      /home/<you>/Desktop/MindGate/...) and are NOT installed as-is.
#   5. Installs the systemd units for the daemon AND its watchdog
#      companion, enables + starts both.
#
# Must be run with sudo — everything here needs root: installing to
# /usr/local/bin and /etc/mindgate, writing systemd units, and the
# daemon itself needs root for the nft/dnsmasq calls in engine.rs.
#
# Re-runnable: safe to run again after a `git pull` to pick up a new
# build — it overwrites its own generated files and re-enables the
# units, it does not touch rules.toml/lock.toml.

set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
  echo "Run this with sudo: sudo ./install.sh" >&2
  exit 1
fi

# Resolves to the repo root regardless of where install.sh is invoked
# from, since it lives at <repo>/installer/install.sh.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_BIN_DIR="/usr/local/bin"
CONFIG_DIR="/etc/mindgate"

# The real, invoking human, even though this script itself is running
# as root under sudo — needed below to find THEIR browser profile
# dirs (~/.config/...), not root's. Falls back to whoever owns the
# terminal if SUDO_USER somehow isn't set (e.g. a root login shell).
REAL_USER="${SUDO_USER:-$(logname 2>/dev/null || echo root)}"
REAL_HOME="$(getent passwd "${REAL_USER}" | cut -d: -f6)"

# Update this if your packed/loaded extension's ID differs — it's
# visible at chrome://extensions with Developer Mode on, and is what
# gates which caller is allowed to talk to the native-messaging bridge
# (see allowed_origins in the generated manifest below).
EXTENSION_ID="echllloajdapolndcjklcnmmkcajomhp"

echo "[1/5] Building release binaries..."
cd "${REPO_ROOT}"
cargo build --release

echo "[2/5] Installing binaries to ${INSTALL_BIN_DIR}..."
install -o root -g root -m 755 target/release/mindgated "${INSTALL_BIN_DIR}/mindgated"
install -o root -g root -m 755 target/release/mindgate  "${INSTALL_BIN_DIR}/mindgate"

echo "[3/5] Creating ${CONFIG_DIR} (root-owned, 700)..."
mkdir -p "${CONFIG_DIR}"
chown root:root "${CONFIG_DIR}"
chmod 700 "${CONFIG_DIR}"

echo "[4/5] Generating production native-messaging bridge + manifest..."
BRIDGE_SCRIPT="${CONFIG_DIR}/mindgate-bridge.sh"
cat > "${BRIDGE_SCRIPT}" <<BRIDGE_EOF
#!/bin/bash
# Generated by install.sh — do not hand-edit, re-run install.sh instead.
# Unlike the dev-mode mindgate.sh this replaces, there is no
# MINDGATE_SOCKET/MINDGATE_CONFIG_DIR override here: the daemon and
# CLI both fall back to their real production paths
# (/run/mindgate/mindgate.sock, /etc/mindgate) when those env vars
# are unset, which is exactly what a real install should use.
exec 2>>/var/log/mindgate-bridge-error.log
exec "${INSTALL_BIN_DIR}/mindgate" nativebridge
BRIDGE_EOF
chmod 755 "${BRIDGE_SCRIPT}"
chown root:root "${BRIDGE_SCRIPT}"

NMH_MANIFEST_NAME="com.mindgate.protector.json"
# Chromium-family profile dirs to check. Firefox uses a DIFFERENT
# manifest key ("allowed_extensions" instead of "allowed_origins") and
# a different install path — deliberately not handled here; ask if
# you also want a Firefox manifest generated.
declare -a NMH_DIRS=(
  "${REAL_HOME}/.config/google-chrome/NativeMessagingHosts"
  "${REAL_HOME}/.config/chromium/NativeMessagingHosts"
  "${REAL_HOME}/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts"
  "${REAL_HOME}/.config/vivaldi/NativeMessagingHosts"
  "${REAL_HOME}/.config/microsoft-edge/NativeMessagingHosts"
)

for dir in "${NMH_DIRS[@]}"; do
  parent="$(dirname "${dir}")"
  [[ -d "${parent}" ]] || continue   # that browser was never installed/run — skip it
  mkdir -p "${dir}"
  cat > "${dir}/${NMH_MANIFEST_NAME}" <<MANIFEST_EOF
{
  "name": "com.mindgate.protector",
  "description": "MindGate Local Native Messaging Bridge",
  "path": "${BRIDGE_SCRIPT}",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://${EXTENSION_ID}/"
  ]
}
MANIFEST_EOF
  chown "${REAL_USER}:${REAL_USER}" "${dir}/${NMH_MANIFEST_NAME}"
  echo "  -> installed manifest for $(basename "${parent}")"
done

echo "[5/5] Installing systemd units (daemon + watchdog) and enabling..."
install -m 644 "${REPO_ROOT}/installer/systemd/mindgated.service" \
  /etc/systemd/system/mindgated.service
install -m 644 "${REPO_ROOT}/installer/systemd/mindgate-watchdog.service" \
  /etc/systemd/system/mindgate-watchdog.service
install -m 755 "${REPO_ROOT}/installer/mindgate-watchdog.sh" \
  "${INSTALL_BIN_DIR}/mindgate-watchdog.sh"

systemctl daemon-reload
systemctl enable --now mindgated.service
systemctl enable --now mindgate-watchdog.service

echo
echo "Done. mindgated + mindgate-watchdog are running and enabled at boot."
echo "Check status with: sudo systemctl status mindgated mindgate-watchdog"
echo
echo "To actually stop MindGate later, both units have to be stopped —"
echo "either one alone gets restarted by the other within ~15s:"
echo "  sudo systemctl stop mindgate-watchdog mindgated"